config/routes.rb
Obelix::Application.routes.draw do

  resources :login

  resources :caixas_postais

  resources :planos_discagens

  resources :ramais

  resources :sip

  resources :iax

  match "monitoramento/ajax" => "monitoramentos#ajax"

  root :to => 'sip#index'

  match ':controller(/:action(/:id))(.:format)'

  

  
end

app/controllers/monitoramentos_controller.rb
class MonitoramentosController < ApplicationController
  before_filter :comandos, :only => [:index,:ajax]
  # GET /monitoramentos
  def index
    respond_to do |format|
      format.html # index.html.erb
    end
  end
  def ajax
  	render :partial => 'monitoramento'
  end
  
  private
  def comandos
	  @sip      = `asterisk -x 'sip show users'`
    @iax      = `asterisk -x 'iax2 show peers'`
  	@peers    = `asterisk -x 'sip show peers'`
   	@channels = `asterisk -x 'core show channels'`	
    @voicemail= `asterisk -x 'voicemail show users for LOCAL'`
  end  
   
end

app/helpers/monitoramentos_helper.rb
module MonitoramentosHelper
end

app/views/monitoramentos/_form.html.erb
<%= form_for(@monitoramento) do |f| %>
  <% if @monitoramento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@monitoramento.errors.count, "error") %> prohibited this monitoramento from being saved:</h2>

      <ul>
      <% @monitoramento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/monitoramentos/_monitoramento.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th style="vertical-align: middle">Iax</th>
      <td><pre><%= @iax%></pre></td>
    </tr>
    <tr>
      <th style="vertical-align: middle">Sip</th>
      <td><pre><%= @peers%></pre></td>
    </tr>

    <tr>
      <th style="vertical-align: middle">Canais</th>
      <td><pre><%= @channels%></pre></td>
    </tr>

    <tr>
      <th style="vertical-align: middle">Canais</th>
      <td><pre><%= @voicemail%></pre></td>
    </tr>

  </thead>
  <tbody>

  </tbody>
</table>

app/views/monitoramentos/edit.html.erb
<h1>Editing monitoramento</h1>

<%= render 'form' %>

<%= link_to 'Show', @monitoramento %> |
<%= link_to 'Back', monitoramentos_path %>

app/views/monitoramentos/index.html.erb
<div class="page-header">
  <h1>Monitoramentos<%#=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<div id="monitoramento">
<%= render :partial => 'monitoramento'  %>
</div>

app/views/monitoramentos/new.html.erb
<h1>New monitoramento</h1>

<%= render 'form' %>

<%= link_to 'Back', monitoramentos_path %>

app/views/monitoramentos/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_monitoramento_path(@monitoramento) %> |
<%= link_to 'Back', monitoramentos_path %>